#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "   __  __ _            "
echo "  |  \/  (_)_____   _  "
echo "  | |\/| | |_  / | | | "
echo "  | |  | | |/ /| |_| | "
echo "  |_|  |_|_/___|\__,_| "
echo ""
echo "  Self-hosting platform for macOS home labs"
echo -e "${NC}"

# Check requirements
echo -e "${YELLOW}Checking requirements...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Docker is required but not installed.${NC}"
    echo "Please install Docker Desktop from https://docker.com"
    exit 1
fi

if ! docker info &> /dev/null; then
    echo -e "${RED}Docker daemon is not running.${NC}"
    echo "Please start Docker Desktop and try again."
    exit 1
fi

echo -e "${GREEN}✓ Docker is available${NC}"

# Create mizu directory
MIZU_DIR="${HOME}/.mizu"
mkdir -p "$MIZU_DIR"
cd "$MIZU_DIR"

echo ""
echo -e "${CYAN}Configuration${NC}"
echo "─────────────────────────────────"

# Get domain
read -p "Enter your domain (e.g., mizu.local): " MIZU_DOMAIN
if [ -z "$MIZU_DOMAIN" ]; then
    MIZU_DOMAIN="localhost"
fi

# Get email for SSL
read -p "Enter your email (for SSL certificates): " MIZU_EMAIL
if [ -z "$MIZU_EMAIL" ]; then
    MIZU_EMAIL="admin@${MIZU_DOMAIN}"
fi

# Generate secrets
echo ""
echo -e "${YELLOW}Generating secrets...${NC}"
MIZU_DB_PASSWORD=$(openssl rand -hex 32)
MIZU_ENCRYPTION_KEY=$(openssl rand -hex 32)
MIZU_AUTH_SECRET=$(openssl rand -hex 32)

# Create .env file
cat > .env << EOF
# Mizu Configuration
# Generated on $(date)

MIZU_DOMAIN=${MIZU_DOMAIN}
MIZU_EMAIL=${MIZU_EMAIL}
MIZU_DB_PASSWORD=${MIZU_DB_PASSWORD}
MIZU_ENCRYPTION_KEY=${MIZU_ENCRYPTION_KEY}
MIZU_AUTH_SECRET=${MIZU_AUTH_SECRET}
EOF

echo -e "${GREEN}✓ Environment file created${NC}"

# Download templates
echo ""
echo -e "${YELLOW}Downloading configuration files...${NC}"

# Create docker-compose.yaml
cat > docker-compose.yaml << 'COMPOSE_EOF'
# Mizu Docker Compose Configuration
# Generated by install.sh - do not edit manually

version: '3.8'

services:
  mizu-proxy:
    image: caddy:2-alpine
    container_name: mizu-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - mizu-app
    networks:
      - mizu-network

  mizu-app:
    image: ghcr.io/mizudev/mizu:latest
    container_name: mizu-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://mizu:${MIZU_DB_PASSWORD}@mizu-db:5432/mizu
      - ENCRYPTION_KEY=${MIZU_ENCRYPTION_KEY}
      - BETTER_AUTH_SECRET=${MIZU_AUTH_SECRET}
      - BETTER_AUTH_URL=https://${MIZU_DOMAIN}
      - MIGRATE_ON_START=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - mizu-db
    networks:
      - mizu-network

  mizu-db:
    image: postgres:16-alpine
    container_name: mizu-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=mizu
      - POSTGRES_PASSWORD=${MIZU_DB_PASSWORD}
      - POSTGRES_DB=mizu
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mizu-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mizu"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  mizu-network:
    driver: bridge
COMPOSE_EOF

# Create Caddyfile with variable placeholders
cat > Caddyfile << CADDY_EOF
{
    email ${MIZU_EMAIL}
    admin off
}

${MIZU_DOMAIN} {
    reverse_proxy mizu-app:3000

    # Security headers
    header {
        X-Content-Type-Options nosniff
        X-Frame-Options DENY
        Referrer-Policy strict-origin-when-cross-origin
        X-XSS-Protection "1; mode=block"
    }

    # Compress responses
    encode gzip zstd

    # Logs
    log {
        output file /var/log/caddy/access.log
        format json
    }
}
CADDY_EOF

echo -e "${GREEN}✓ Configuration files created${NC}"

# Pull images
echo ""
echo -e "${YELLOW}Pulling Docker images...${NC}"
docker compose pull

# Start services
echo ""
echo -e "${YELLOW}Starting Mizu...${NC}"
docker compose up -d

# Wait for health
echo ""
echo -e "${YELLOW}Waiting for services to be ready...${NC}"
sleep 10

# Check if running
if docker compose ps | grep -q "running"; then
    echo ""
    echo -e "${GREEN}════════════════════════════════════════${NC}"
    echo -e "${GREEN}       Mizu is now running!             ${NC}"
    echo -e "${GREEN}════════════════════════════════════════${NC}"
    echo ""
    echo -e "Open ${CYAN}https://${MIZU_DOMAIN}${NC} in your browser"
    echo ""
    echo "Configuration saved to: ${MIZU_DIR}"
    echo ""
    echo -e "${YELLOW}First-time setup:${NC}"
    echo "1. Create your admin account at the setup wizard"
    echo "2. Start deploying your services!"
    echo ""
else
    echo -e "${RED}Something went wrong. Check logs with:${NC}"
    echo "docker compose logs"
    exit 1
fi
