import type { ProjectManifest } from './types'

/**
 * Generate a .env file from a project manifest.
 * Contains actual secret values.
 */
export function generateEnvFile(manifest: ProjectManifest): string {
  const lines: string[] = [
    '# Generated by Mizu',
    `# Project: ${manifest.project.name}`,
    '# WARNING: This file contains secrets. Do not commit to version control.',
    '',
  ]

  // Collect all environment variables
  const envVars: Record<string, string> = {}

  // From services
  for (const service of manifest.services) {
    if (service.envVars) {
      try {
        const parsed = JSON.parse(service.envVars) as Record<string, string>
        Object.assign(envVars, parsed)
      } catch {
        // Invalid JSON
      }
    }
  }

  // From env groups
  for (const group of manifest.envGroups) {
    if (group.values) {
      try {
        const parsed = JSON.parse(group.values) as Record<string, string>
        // Add prefix if group name suggests namespacing
        const prefix = group.isSecret ? '' : `${group.name.toUpperCase()}_`
        for (const [key, value] of Object.entries(parsed)) {
          envVars[prefix + key] = value
        }
      } catch {
        // Invalid JSON
      }
    }
  }

  // From database credentials
  for (const database of manifest.databases) {
    if (database.credentials) {
      try {
        const creds = JSON.parse(database.credentials) as Record<string, string>
        const prefix = `${database.name.toUpperCase()}_DB_`
        for (const [key, value] of Object.entries(creds)) {
          envVars[prefix + key.toUpperCase()] = value
        }
      } catch {
        // Invalid JSON
      }
    }
  }

  // From external services
  for (const ext of manifest.externalServices) {
    if (ext.credentials) {
      try {
        const creds = JSON.parse(ext.credentials) as Record<string, string>
        const prefix = `${ext.name.toUpperCase()}_`
        for (const [key, value] of Object.entries(creds)) {
          envVars[prefix + key.toUpperCase()] = value
        }
      } catch {
        // Invalid JSON
      }
    }
  }

  // Sort and output
  const sortedKeys = Object.keys(envVars).sort()
  for (const key of sortedKeys) {
    const value = envVars[key]
    if (value === undefined) continue
    // Quote values with special characters
    const needsQuotes = /[\s#"'$\\]/.test(value)
    lines.push(needsQuotes ? `${key}="${value}"` : `${key}=${value}`)
  }

  return `${lines.join('\n')}\n`
}

/**
 * Generate a .env.example file from a project manifest.
 * Contains placeholder values instead of secrets.
 */
export function generateEnvExampleFile(manifest: ProjectManifest): string {
  const lines: string[] = [
    '# Environment variables for this project',
    `# Project: ${manifest.project.name}`,
    '# Copy this file to .env and fill in the values.',
    '',
  ]

  // Collect all environment variable keys
  const envKeys = new Set<string>()

  // From services
  for (const service of manifest.services) {
    if (service.envVars) {
      try {
        const parsed = JSON.parse(service.envVars) as Record<string, string>
        for (const k of Object.keys(parsed)) {
          envKeys.add(k)
        }
      } catch {
        // Invalid JSON
      }
    }
  }

  // From env groups
  for (const group of manifest.envGroups) {
    if (group.values) {
      try {
        const parsed = JSON.parse(group.values) as Record<string, string>
        const prefix = group.isSecret ? '' : `${group.name.toUpperCase()}_`
        for (const k of Object.keys(parsed)) {
          envKeys.add(prefix + k)
        }
      } catch {
        // Invalid JSON
      }
    }
  }

  // From database credentials
  for (const database of manifest.databases) {
    const prefix = `${database.name.toUpperCase()}_DB_`
    envKeys.add(`${prefix}USERNAME`)
    envKeys.add(`${prefix}PASSWORD`)
    envKeys.add(`${prefix}DATABASE`)
  }

  // From external services
  for (const ext of manifest.externalServices) {
    const prefix = `${ext.name.toUpperCase()}_`
    envKeys.add(`${prefix}API_KEY`)
    envKeys.add(`${prefix}HOST`)
  }

  // Sort and output with placeholders
  const sortedKeys = Array.from(envKeys).sort()
  for (const key of sortedKeys) {
    const placeholder = getPlaceholder(key)
    lines.push(`${key}=${placeholder}`)
  }

  return `${lines.join('\n')}\n`
}

/**
 * Generate a placeholder value based on the key name.
 */
function getPlaceholder(key: string): string {
  const lowerKey = key.toLowerCase()

  if (lowerKey.includes('password')) return 'your-password-here'
  if (lowerKey.includes('secret')) return 'your-secret-here'
  if (lowerKey.includes('api_key') || lowerKey.includes('apikey')) return 'your-api-key-here'
  if (lowerKey.includes('token')) return 'your-token-here'
  if (lowerKey.includes('host')) return 'localhost'
  if (lowerKey.includes('port')) return '3000'
  if (lowerKey.includes('database') || lowerKey.includes('db_name')) return 'mydb'
  if (lowerKey.includes('username') || lowerKey.includes('user')) return 'myuser'
  if (lowerKey.includes('url')) return 'https://example.com'

  return 'your-value-here'
}
