import yaml from 'js-yaml'
import type { DockerComposeFile, GenerationOptions, ProjectManifest } from '../types'
import { getDatabaseVolumes, transformDatabase } from './database-transformer'
import { transformNetworks } from './network-transformer'
import { transformService } from './service-transformer'
import { transformVolumes } from './volume-transformer'

/**
 * Generate a docker-compose.yml file from a project manifest.
 *
 * The canvas is a visual docker-compose.yml representation.
 * This function transforms the canvas entities back into YAML.
 */
export function generateDockerCompose(
  manifest: ProjectManifest,
  options: GenerationOptions = {},
): string {
  const { includeComments = true, profile } = options
  const commonNetworkName = `${manifest.project.slug}-common`

  // Build env groups map for service transformer
  const envGroups = new Map<string, Record<string, string>>()
  for (const group of manifest.envGroups) {
    if (group.values) {
      try {
        const parsed = JSON.parse(group.values) as Record<string, string>
        envGroups.set(group.id, parsed)
      } catch {
        // Invalid JSON
      }
    }
  }

  const serviceNameById = new Map(manifest.services.map((service) => [service.id, service.name]))
  const databaseNameById = new Map(
    manifest.databases.map((database) => [database.id, database.name]),
  )
  const networkNameById = new Map(manifest.networks.map((network) => [network.id, network.name]))

  // Transform services
  const services: DockerComposeFile['services'] = {}

  for (const service of manifest.services) {
    services[service.name] = transformService(
      service,
      manifest.connections,
      manifest.volumes,
      envGroups,
      {
        serviceNameById,
        databaseNameById,
        networkNameById,
        commonNetworkName,
      },
    )
  }

  // Transform databases to services
  for (const database of manifest.databases) {
    services[database.name] = transformDatabase(database, commonNetworkName)
  }

  // Transform networks
  const customNetworks = transformNetworks(manifest.networks)
  const networks = {
    [commonNetworkName]: {},
    ...customNetworks,
  }

  // Transform volumes (user-defined + database volumes)
  const userVolumes = transformVolumes(manifest.volumes)
  const dbVolumes = getDatabaseVolumes(manifest.databases)
  const volumes = { ...userVolumes, ...dbVolumes }

  // Build the compose file
  const composeFile: DockerComposeFile = {
    name: manifest.project.slug,
    services,
  }

  composeFile.networks = networks

  // Only include volumes if there are any
  if (Object.keys(volumes).length > 0) {
    composeFile.volumes = volumes
  }

  // Convert to YAML
  let yamlContent = yaml.dump(composeFile, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
    quotingType: '"',
    forceQuotes: false,
  })

  // Add header comment
  if (includeComments) {
    const header = [
      '# Generated by Mizu - https://mizu.dev',
      `# Project: ${manifest.project.name}`,
      `# Workspace: ${manifest.workspace.name}`,
      profile ? `# Profile: ${profile}` : null,
      '#',
      '# This file is auto-generated from the Mizu canvas.',
      '# Edit the canvas in Mizu to make changes.',
      '#',
      '',
    ]
      .filter(Boolean)
      .join('\n')

    yamlContent = header + yamlContent
  }

  return yamlContent
}

export { getDatabaseVolumes, transformDatabase } from './database-transformer'
export { transformNetwork, transformNetworks } from './network-transformer'
export { transformService } from './service-transformer'
export { transformVolume, transformVolumes } from './volume-transformer'
